### PR TITLE
Small fix to account for empty lists of star values.

### PR DESCRIPTION
**Pull request by HorstmannA**
Stop the pipeline breaking if it gets an empty list from reading a star file.

### CODE REVIEW

**Comment by d-j-hatton** [comment]
Was the problem that `_request_star_values` was crashing or that it was returning `None`?

**Comment by HorstmannA** [comment]
I think None - this was the error: 
"Invoked with: <gemmi.cif.Document with 0 blocks ()>, None"

**Comment by d-j-hatton** [comment]
Can you see if there was a `TypeError` in the traceback before that? I think this is something `gemmi` throws if you do something like `stra_doc[None]`, but there is an `except` for `TypeError`  in the `origin_present` function that the wrapper uses that should catch that. Do you know if it was `origin_present` or just `relion_prj.load()` that ultimately caused it?

**Comment by HorstmannA** [comment]
The TypeError says 
`TypeError: __getitem__(): incompatible function arguments.`

Full trace:
`__getitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: gemmi.cif.Document, name: str) -> gemmi.cif.Block
    2. (self: gemmi.cif.Document, index: int) -> gemmi.cif.Block
    3. (self: gemmi.cif.Document, arg0: slice) -> list

Invoked with: <gemmi.cif.Document with 0 blocks ()>, None
Traceback (most recent call last):
  File "/home/slg25752/dials/dlstbx/src/dlstbx/cli/wrap.py", line 182, in run
    if instance.run():
  File "/home/slg25752/dials/relion/src/relion/zocalo/wrapper.py", line 100, in run
    relion_prj.load()
  File "/home/slg25752/dials/relion/src/relion/__init__.py", line 112, in load
    self.load_nodes_from_star(self.basepath / "default_pipeline.star")
  File "/home/slg25752/dials/relion/src/relion/_parser/relion_pipeline.py", line 69, in load_nodes_from_star
    file_nodes = self._load_file_nodes_from_star(star_path)
  File "/home/slg25752/dials/relion/src/relion/_parser/relion_pipeline.py", line 52, in _load_file_nodes_from_star
    for p in self._request_star_values(star_path, "_rlnPipeLineNodeName")
  File "/home/slg25752/dials/relion/src/relion/_parser/relion_pipeline.py", line 44, in _request_star_values
    data_block = star_doc[block_number]
TypeError: __getitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: gemmi.cif.Document, name: str) -> gemmi.cif.Block
    2. (self: gemmi.cif.Document, index: int) -> gemmi.cif.Block
    3. (self: gemmi.cif.Document, arg0: slice) -> list

Invoked with: <gemmi.cif.Document with 0 blocks ()>, None`

**Comment by d-j-hatton** [comment]
Seems quite nasty. It seems like it crashed because it didn't find anything in `default_pipeline.star` after it has passed a check on whether there is anything in `default_pipeline.star`. Does it happen every time you run the wrapper or just sometimes?

**Comment by HorstmannA** [comment]
I think only sometimes. It worked a few times this morning then threw this error a few times. Markus suggested it could be a race condition, we don't have a way of checking if Relion has actually finished writing to a file. `default_pipeline.star` could feasibly be empty at certain times.

**Comment by d-j-hatton** [comment]
Yes, I was thinking something like that because Colin mentioned the possibility

**Comment by d-j-hatton** [comment]
Along with this fix I'd suggest adding 
```
if len(self._nodes) == 0:
    return False
```
to `origin_present()` after [line 107](https://github.com/DiamondLightSource/python-relion/blob/50a8569558fc2f721c729d5b4442f960942e1019/src/relion/__init__.py#L107) in `__init__` so that that function should behave as before (when it relied on the `None` causing a `TypeError`).

**Comment by HorstmannA** [comment]
Okay cheers, will do

**Review by Anthchirp — APPROVED** [review]

**Pull request merged**
